version: '3.1'

services:
    redmine:
      image: redmine:4.1
      restart: always
      ports:
        - 80:3000
      environment:
        REDMINE_DB_MYSQL: db
        REDMINE_DB_PASSWORD: example

    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: redmine
      volumes:
        - db-data:/var/lib/mysql/data

volumes:
  db-data:
