version: 2.1
jobs:
  lint:
    working_directory: ~/redshape
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: 'sudo apt install libxss-dev pkg-config'
      - run:
          name: Install Dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'Linting'
          command: yarn lint

  test:
    working_directory: ~/redshape
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: 'sudo apt-get update'
      - run: 'sudo apt install libxss-dev libxext-dev libxtst6 libnss3 libgtk-3-0 libgtkextra-dev libasound2'
      - run:
          name: Install Dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Coverage
          command: 'yarn test'

  build-windows:
    working_directory: ~/redshape
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              yarn release -- -w --ia32 --x64
            elif [ "$CIRCLE_BRANCH" == "develop" ]; then
              yarn release:ci -- -w --ia32 --x64
            else
              yarn build -- -w --ia32 --x64
            fi
      - store_artifacts:
          path: ~/redshape/build

  build-linux:
    working_directory: ~/redshape
    docker:
      - image: electronuserland/builder
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: 'yarn install --pure-lockfile'
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              yarn release -- -l --ia32 --x64
            elif [ "$CIRCLE_BRANCH" == "develop" ]; then
              yarn release:ci -- -l --ia32 --x64
            else
              yarn build -- -l --ia32 --x64
            fi
      - store_artifacts:
          path: ~/redshape/build

workflows:
  test:
    jobs:
      - lint
      - test
  build:
    jobs:
      - build-windows:
        filters:
          branches:
            ignore:
              - /^v\\d+\\.\\d+\\.\\d+$/
      - build-linux:
        filters:
          branches:
            ignore:
              - /^v\\d+\\.\\d+\\.\\d+$/
