version: 2
jobs:
  lint:
    working_directory: ~/redshape
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: 'sudo apt install libxss-dev pkg-config'
      - run:
          name: Install Dependencies
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: 'Linting'
          command: 'npm run lint'

  test:
    working_directory: ~/redshape
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: 'sudo apt install libxss-dev pkg-config'
      - run:
          name: Install Dependencies
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Coverage
          command: 'npm test'

workflows:
  version: 2
  test-cover-push:
    jobs:
      - lint
      - test
